
# experiment basic
#origin_lat: 33.59554271426774
#origin_lng: 130.21900769548205

#origin_lat: 33.595542
#origin_lng: 130.219007
#angle_offset: 42.84752885475223

#origin_lat: 33.2401315617
#origin_lng: 130.616078625
#angle_offset: -125.0

##scale_offset: 1.0002455054972383
#scale_offset: 1.000

# demo 20201028
#origin_lat: 33.598533
#origin_lng: 130.223897
#angle_offset: -108.5
#scale_offset: 1.000


#fix_value: 3
#float_value: 2

/**:
    ros__parameters:
        ## Ito Cumpus Square
        #origin_lat: 33.595542
        #origin_lng: 130.219007
        #angle_offset: 42.85
        #scale_offset: 1.0

        ## experiment 20210203
        #origin_lat: 33.2401315617
        #origin_lng: 130.616078625
        #angle_offset: -125.0
        #scale_offset: 1.0

        ## Ito Cumpus Square (angle = 0.0)
        #origin_lat: 33.595300
        #origin_lng: 130.218900
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## W2 Ura Gravel
        #origin_lat: 33.596200
        #origin_lng: 130.218400
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20210803
        #origin_lat: 33.600100
        #origin_lng: 130.206600
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20210819 Ito Cumpus Ground
        #origin_lat: 33.600500
        #origin_lng: 130.206600
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20211029 Ito Cumpus Ground
        #origin_lat: 33.600000
        #origin_lng: 130.206300
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20211129 farm
        #angle_offset: 0.0
        #scale_offset: 1.0
        # 1
        #origin_lat: 33.250684
        #origin_lng: 130.581483
        # 2
        #origin_lat: 33.251066
        #origin_lng: 130.581475
        # 3
        #origin_lat: 33.251282
        #origin_lng: 130.581512
        # 4
        #origin_lat: 33.250798
        #origin_lng: 130.581051
        # 5
        #origin_lat: 33.251873
        #origin_lng: 130.584095
        # 6
        #origin_lat: 33.232414
        #origin_lng: 130.526730
        # 7
        #origin_lat: 33.233486
        #origin_lng: 130.526649

        ## experiment karadomari village
        origin_lat: 33.649500
        origin_lng: 130.232400
        angle_offset: 25.0 # 刈り取る方向が時計回りにかわる
        scale_offset: 1.0
