
# experiment basic
#origin_lat: 33.59554271426774
#origin_lng: 130.21900769548205

#origin_lat: 33.595542
#origin_lng: 130.219007
#angle_offset: 42.84752885475223

#origin_lat: 33.2401315617
#origin_lng: 130.616078625
#angle_offset: -125.0

##scale_offset: 1.0002455054972383
#scale_offset: 1.000

# demo 20201028
#origin_lat: 33.598533
#origin_lng: 130.223897
#angle_offset: -108.5
#scale_offset: 1.000


#fix_value: 3
#float_value: 2

/**:
    ros__parameters:
        ## Ito Cumpus Square
        #origin_lat: 33.595542
        #origin_lng: 130.219007
        #angle_offset: 42.85
        #scale_offset: 1.0

        ## experiment 20210203
        #origin_lat: 33.2401315617
        #origin_lng: 130.616078625
        #angle_offset: -125.0
        #scale_offset: 1.0

        ## Ito Cumpus Square (angle = 0.0)
        #origin_lat: 33.595300
        #origin_lng: 130.218900
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## W2 Ura Gravel
        #origin_lat: 33.596200
        #origin_lng: 130.218400
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20210803
        #origin_lat: 33.600100
        #origin_lng: 130.206600
        #angle_offset: 0.0
        #scale_offset: 1.0

        ## experiment 20210819
        origin_lat: 33.600500
        origin_lng: 130.206600
        angle_offset: 0.0
        scale_offset: 1.0
